name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
env:
  RUST_BACKTRACE: 1
jobs:
  test:
    name: Test ${{ matrix.target }}
    strategy:
      fail-fast: true
      matrix:
        include:
          #- { target: x86_64-pc-windows-msvc, os: windows-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          #- { target: x86_64-apple-darwin, os: macos-latest }
          #- {
              #target: x86_64-pc-windows-gnu,
              #os: windows-latest,
              #host: -x86_64-pc-windows-gnu,
            #}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # This has a matcher for test panics, so we use it even though elsewhere
      # we use actions-rs/toolchain.
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable${{ matrix.host }}
          targets: ${{ matrix.target }}
          components: 'rustfmt, clippy'

      - uses: katyo/publish-crates@octokit-less
        name: cargo publish
        with:
          path: './'
          args: --allow-dirty --all-features
          dry-run: true
